# Generated by Django 3.2.12 on 2022-05-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
