# Generated by Django 3.2.12 on 2022-05-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220521_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres_string',
        ),
    ]
