# Generated by Django 3.2.12 on 2022-05-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220521_0133'),
        ('movies', '0002_auto_20220522_1438'),
    ]

    operations = [
    ]
