# Generated by Django 3.2.12 on 2022-05-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_merge_0002_auto_20220521_0133_0002_auto_20220522_1438'),
        ('movies', '0003_remove_movie_genres_string'),
    ]

    operations = [
    ]
